import { Job } from './store'

export const mockJobs: Job[] = [
  {
    id: 'job1',
    title: 'Bathroom Renovation',
    description: 'Complete bathroom renovation including tiling, fixtures, and painting. Need experienced professional with references.',
    category: 'Construction',
    budget: 250000,
    location: 'Central Wukari',
    employerId: 'emp1',
    status: 'open',
    applicants: ['worker1', 'worker2'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job2',
    title: 'Plumbing Repair',
    description: 'Fix burst pipes and install new fixtures in kitchen. Urgent job, need someone ASAP.',
    category: 'Plumbing',
    budget: 45000,
    location: 'North Wukari',
    employerId: 'emp2',
    status: 'open',
    applicants: ['worker3'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job3',
    title: 'House Cleaning',
    description: '4-bedroom house cleaning, deep clean including windows, carpets, and all surfaces.',
    category: 'Cleaning',
    budget: 35000,
    location: 'South Wukari',
    employerId: 'emp3',
    status: 'open',
    applicants: [],
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job4',
    title: 'Electrical Wiring',
    description: 'Install new electrical wiring throughout renovated office space. Must have certification.',
    category: 'Electrical',
    budget: 180000,
    location: 'Central Wukari',
    employerId: 'emp1',
    status: 'open',
    applicants: ['worker5', 'worker6', 'worker7'],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job5',
    title: 'Fence Repair',
    description: 'Repair damaged fence sections and paint. About 50 meters of fencing.',
    category: 'Construction',
    budget: 75000,
    location: 'North Wukari',
    employerId: 'emp4',
    status: 'open',
    applicants: ['worker2'],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job6',
    title: 'Door Installation',
    description: 'Install new security doors and locks on 3 entrances. Modern design preferred.',
    category: 'Construction',
    budget: 95000,
    location: 'Central Wukari',
    employerId: 'emp5',
    status: 'open',
    applicants: ['worker8'],
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job7',
    title: 'Roof Repairs',
    description: 'Fix leaking roof and replace damaged tiles. Sloped roof, 6x8 meters.',
    category: 'Repairs',
    budget: 120000,
    location: 'South Wukari',
    employerId: 'emp6',
    status: 'open',
    applicants: ['worker4', 'worker9'],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job8',
    title: 'Window Replacement',
    description: 'Replace 12 old windows with new modern energy-efficient ones.',
    category: 'Construction',
    budget: 88000,
    location: 'North Wukari',
    employerId: 'emp7',
    status: 'open',
    applicants: [],
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
]
