import type { Job, Booking, Notification, Transaction, Shop } from './store'
import { DEFAULT_HOURS } from './store'

export const mockJobs: Job[] = [
  {
    id: 'job1',
    title: 'Bathroom Renovation',
    description: 'Complete bathroom renovation including tiling, fixtures, and painting. Need experienced professional with references.',
    category: 'Construction',
    budget: 250000,
    location: 'Central Wukari',
    employerId: 'emp1',
    status: 'open',
    applicants: ['worker1', 'worker2'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job2',
    title: 'Plumbing Repair',
    description: 'Fix burst pipes and install new fixtures in kitchen. Urgent job, need someone ASAP.',
    category: 'Plumbing',
    budget: 45000,
    location: 'North Wukari',
    employerId: 'emp2',
    status: 'open',
    applicants: ['worker3'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job3',
    title: 'House Cleaning',
    description: '4-bedroom house deep clean including windows, carpets, and all surfaces.',
    category: 'Cleaning',
    budget: 35000,
    location: 'South Wukari',
    employerId: 'emp3',
    status: 'open',
    applicants: [],
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job4',
    title: 'Electrical Wiring',
    description: 'Install new electrical wiring throughout renovated office space. Must have certification.',
    category: 'Electrical',
    budget: 180000,
    location: 'Central Wukari',
    employerId: 'emp1',
    status: 'open',
    applicants: ['worker5', 'worker6', 'worker7'],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job5',
    title: 'Fence Repair & Painting',
    description: 'Repair damaged fence sections and repaint. About 50 meters of fencing.',
    category: 'Construction',
    budget: 75000,
    location: 'North Wukari',
    employerId: 'emp4',
    status: 'open',
    applicants: ['worker2'],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job6',
    title: 'Security Door Installation',
    description: 'Install new security doors and locks on 3 entrances. Modern design preferred.',
    category: 'Construction',
    budget: 95000,
    location: 'Central Wukari',
    employerId: 'emp5',
    status: 'open',
    applicants: ['worker8'],
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job7',
    title: 'Roof Repairs',
    description: 'Fix leaking roof and replace damaged tiles. Sloped roof, 6x8 meters.',
    category: 'Repairs',
    budget: 120000,
    location: 'South Wukari',
    employerId: 'emp6',
    status: 'open',
    applicants: ['worker4', 'worker9'],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job8',
    title: 'Window Replacement',
    description: 'Replace 12 old windows with new modern energy-efficient ones.',
    category: 'Construction',
    budget: 88000,
    location: 'North Wukari',
    employerId: 'emp7',
    status: 'open',
    applicants: [],
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'job9',
    title: 'Generator Repair',
    description: 'Service and repair 10KVA generator. Not starting, possible fuel pump issue.',
    category: 'Electrical',
    budget: 28000,
    location: 'South Wukari',
    employerId: 'emp8',
    status: 'open',
    applicants: [],
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'job10',
    title: 'Office Painting',
    description: 'Paint 5-room office space. Walls and ceiling. Client will supply paint.',
    category: 'Repairs',
    budget: 60000,
    location: 'Central Wukari',
    employerId: 'emp9',
    status: 'open',
    applicants: ['worker1'],
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockBookings: Booking[] = [
  {
    id: 'booking1',
    type: 'job',
    jobId: 'job1',
    jobTitle: 'Bathroom Renovation',
    workerId: 'worker1',
    workerName: 'Chukwu Okonkwo',
    employerId: 'emp1',
    employerName: 'Amaka Nwosu',
    status: 'confirmed',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    slots: ['9:00 AM', '10:00 AM', '11:00 AM'],
    totalPrice: 250000,
    negotiated: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'booking2',
    type: 'shop',
    shopId: 'shop1',
    shopName: "Hassan's Barbershop",
    serviceId: 'svc1',
    serviceName: 'Haircut',
    workerId: 'worker_hassan',
    workerName: 'Hassan Abubakar',
    employerId: 'emp3',
    employerName: 'Tunde Oluwaseun',
    status: 'confirmed',
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    slots: ['10:00 AM'],
    totalPrice: 1500,
    negotiated: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'booking3',
    type: 'job',
    jobId: 'job2',
    jobTitle: 'Plumbing Repair',
    workerId: 'worker3',
    workerName: 'Ibrahim Musa',
    employerId: 'emp2',
    employerName: 'Grace Adeyemi',
    status: 'completed',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    slots: ['10:00 AM', '11:00 AM', '12:00 PM'],
    totalPrice: 45000,
    negotiated: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif1',
    type: 'application',
    title: 'New Application Received',
    body: 'Chukwu Okonkwo applied for your Bathroom Renovation job.',
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif2',
    type: 'booking',
    title: 'Booking Confirmed',
    body: 'Your booking for House Cleaning on Friday has been confirmed.',
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif3',
    type: 'message',
    title: 'New Message',
    body: 'Fatima sent you a message: "I can start on Monday, is that okay?"',
    read: true,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif4',
    type: 'payment',
    title: 'Payment Released',
    body: '₦45,000 has been released to your wallet for Plumbing Repair.',
    read: true,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif5',
    type: 'review',
    title: 'New Review',
    body: 'Tunde left you a 5-star review: "Very professional and fast!"',
    read: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: 'tx1',
    type: 'earned',
    amount: 45000,
    jobTitle: 'Plumbing Repair',
    counterpartyName: 'Grace Adeyemi',
    status: 'completed',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx2',
    type: 'escrow',
    amount: 250000,
    jobTitle: 'Bathroom Renovation',
    counterpartyName: 'Amaka Nwosu',
    status: 'held',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx3',
    type: 'earned',
    amount: 60000,
    jobTitle: 'Office Painting',
    counterpartyName: 'Daniel Obi',
    status: 'completed',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockShops: Shop[] = [
  {
    id: 'shop1',
    ownerId: 'worker_hassan',
    ownerName: 'Hassan Abubakar',
    ownerUsername: 'hassan_cuts',
    name: "Hassan's Barbershop",
    category: 'Barbing',
    description: 'Premium cuts and grooming in the heart of Wukari. Walk-ins welcome, booking preferred. Over 7 years giving the cleanest fades in town.',
    location: '12 Market Road, Central Wukari',
    isMobile: false,
    phone: '08012345678',
    services: [
      { id: 'svc1', name: 'Haircut', description: 'Clean fade or scissors cut', price: 1500, pricingType: 'fixed', durationMinutes: 30 },
      { id: 'svc2', name: 'Full Shave', description: 'Head shave with hot towel finish', price: 2000, pricingType: 'fixed', durationMinutes: 45 },
      { id: 'svc3', name: 'Haircut + Beard Trim', description: 'Full grooming package', price: 2500, pricingType: 'fixed', durationMinutes: 60 },
      { id: 'svc4', name: 'Kids Haircut', description: 'Under 12 years', price: 1000, pricingType: 'fixed', durationMinutes: 20 },
    ],
    openingHours: {
      ...DEFAULT_HOURS,
      sun: { open: false, from: '09:00', to: '13:00' },
    },
    rating: 4.9,
    reviewCount: 47,
    reviews: [
      { id: 'rev1', userId: 'emp1', userName: 'Amaka Nwosu', rating: 5, comment: 'Best barber in Wukari, always clean and sharp.', createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
      { id: 'rev2', userId: 'emp2', userName: 'Tunde Bello', rating: 5, comment: 'Fast, clean, professional. Highly recommend.', createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { id: 'rev3', userId: 'emp4', userName: 'Yemi Adeyemi', rating: 4, comment: 'Good cut, was a bit busy when I went but worth the wait.', createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    isOpen: true,
    verified: true,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'shop2',
    ownerId: 'worker2',
    ownerName: 'Fatima Abdullahi',
    ownerUsername: 'fatima_clean',
    name: "Fatima's Cleaning Services",
    category: 'Cleaning',
    description: 'Professional home and office cleaning. Trusted by over 20 families in Wukari. Eco-friendly products, thorough and reliable.',
    location: 'North Wukari',
    isMobile: true,
    phone: '08098765432',
    services: [
      { id: 'svc5', name: 'Standard Home Clean', description: '2–3 bedroom home, all surfaces', price: 15000, pricingType: 'fixed', durationMinutes: 180 },
      { id: 'svc6', name: 'Deep Clean', description: 'Full deep clean including inside appliances', price: 25000, pricingType: 'fixed', durationMinutes: 300 },
      { id: 'svc7', name: 'Office Cleaning', description: 'Price varies by office size', price: 10000, pricingType: 'negotiable', durationMinutes: 120 },
      { id: 'svc8', name: 'Weekly Package', description: '4 visits per month, discounted rate', price: 40000, pricingType: 'negotiable', durationMinutes: 180 },
    ],
    openingHours: {
      ...DEFAULT_HOURS,
      sat: { open: true, from: '08:00', to: '14:00' },
      sun: { open: false, from: '09:00', to: '13:00' },
    },
    rating: 4.8,
    reviewCount: 62,
    reviews: [
      { id: 'rev4', userId: 'emp3', userName: 'Grace Okonkwo', rating: 5, comment: 'Fatima is thorough and trustworthy. My house sparkles every time.', createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { id: 'rev5', userId: 'emp5', userName: 'Musa Bello', rating: 5, comment: 'Very professional. Came on time, did an excellent job.', createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    isOpen: true,
    verified: true,
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'shop3',
    ownerId: 'worker_ngozi',
    ownerName: 'Ngozi Eze',
    ownerUsername: 'ngozi_fashion',
    name: 'Ngozi Fashion House',
    category: 'Tailoring',
    description: 'Bespoke tailoring and alterations. Specialising in traditional and modern styles. Based in Central Wukari — walk in or book ahead.',
    location: '5 Zaria Street, Central Wukari',
    isMobile: false,
    phone: '08055512345',
    services: [
      { id: 'svc9', name: 'Agbada (Full set)', description: 'Sewn to your measurements, 5–7 day turnaround', price: 35000, pricingType: 'negotiable', durationMinutes: 0 },
      { id: 'svc10', name: 'Senator Outfit', description: 'Cap + trousers + shirt', price: 18000, pricingType: 'fixed', durationMinutes: 0 },
      { id: 'svc11', name: 'Ankara Gown', description: "Women's gown, any style", price: 12000, pricingType: 'negotiable', durationMinutes: 0 },
      { id: 'svc12', name: 'Alterations', description: 'Repairs and adjustments to existing garments', price: 3000, pricingType: 'negotiable', durationMinutes: 0 },
    ],
    openingHours: {
      ...DEFAULT_HOURS,
      sun: { open: false, from: '09:00', to: '13:00' },
    },
    rating: 4.7,
    reviewCount: 34,
    reviews: [
      { id: 'rev6', userId: 'emp4', userName: 'Daniel Musa', rating: 5, comment: 'My senator came out perfectly. Very skilled and patient.', createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString() },
      { id: 'rev7', userId: 'emp6', userName: 'Aisha Garba', rating: 5, comment: 'Beautiful ankara gown, exactly what I described. Will be back!', createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    isOpen: true,
    verified: false,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'shop4',
    ownerId: 'worker8',
    ownerName: 'Bello Abubakar',
    ownerUsername: 'bello_mechanic',
    name: 'Bello Auto & Generator',
    category: 'Auto Repair',
    description: 'Auto mechanic and generator technician. Mobile workshop — we come to you anywhere in Wukari. 12 years experience, honest pricing.',
    location: 'Mobile — comes to you',
    isMobile: true,
    phone: '08133334444',
    services: [
      { id: 'svc13', name: 'Generator Service', description: 'Full service and oil change', price: 8000, pricingType: 'fixed', durationMinutes: 90 },
      { id: 'svc14', name: 'Generator Repair', description: 'Diagnosis + repair, price depends on fault', price: 5000, pricingType: 'negotiable', durationMinutes: 120 },
      { id: 'svc15', name: 'Car Service', description: 'Oil, filters, basic check', price: 12000, pricingType: 'negotiable', durationMinutes: 120 },
      { id: 'svc16', name: 'AC Repair', description: 'Home or car AC diagnosis and repair', price: 8000, pricingType: 'negotiable', durationMinutes: 90 },
    ],
    openingHours: {
      ...DEFAULT_HOURS,
      sun: { open: true, from: '10:00', to: '14:00' },
    },
    rating: 4.7,
    reviewCount: 28,
    reviews: [
      { id: 'rev8', userId: 'emp7', userName: 'Emeka Okafor', rating: 5, comment: 'Fixed my generator same day. Fast and fair price.', createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    isOpen: true,
    verified: true,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'shop5',
    ownerId: 'worker_ngozi2',
    ownerName: 'Ngozi Obi',
    ownerUsername: 'ngozi_kitchen',
    name: "Ngozi's Kitchen",
    category: 'Cooking',
    description: 'Event catering and daily home cooking. Hygiene-certified. Available for parties, offices, and families across Wukari.',
    location: 'Central Wukari',
    isMobile: true,
    phone: '08177778888',
    services: [
      { id: 'svc17', name: 'Event Catering (per head)', description: 'Minimum 20 people. Includes setup.', price: 3500, pricingType: 'negotiable', durationMinutes: 0 },
      { id: 'svc18', name: 'Daily Home Cooking', description: 'Cook in your home, 1–2 hrs per session', price: 5000, pricingType: 'fixed', durationMinutes: 120 },
      { id: 'svc19', name: 'Weekly Meal Prep', description: '5 days of meals for a family of 4', price: 25000, pricingType: 'negotiable', durationMinutes: 0 },
      { id: 'svc20', name: 'Small Chops / Finger Food', description: 'For events and parties', price: 8000, pricingType: 'negotiable', durationMinutes: 0 },
    ],
    openingHours: {
      ...DEFAULT_HOURS,
      sun: { open: true, from: '08:00', to: '15:00' },
    },
    rating: 5.0,
    reviewCount: 81,
    reviews: [
      { id: 'rev9', userId: 'emp5', userName: 'Aminu Garba', rating: 5, comment: "Catered my daughter's wedding. Everyone loved the food!", createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
      { id: 'rev10', userId: 'emp8', userName: 'Blessing Obi', rating: 5, comment: 'Best jollof rice in Wukari, no arguments.', createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    isOpen: false,
    verified: true,
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export interface Worker {
  id: string
  name: string
  username: string
  role: 'worker'
  bio: string
  skills: string[]
  rating: number
  completedJobs: number
  location: string
  available: boolean
  hourlyRate: number
  shopId?: string
}

export const mockWorkers: Worker[] = [
  {
    id: 'worker1',
    name: 'Chukwu Okonkwo',
    username: 'chukwu_plumbing',
    role: 'worker',
    bio: '8 years plumbing experience, residential and commercial. Based in Central Wukari. Fast, clean work.',
    skills: ['Plumbing', 'Pipe Fitting', 'Tiling'],
    rating: 4.9,
    completedJobs: 34,
    location: 'Central Wukari',
    available: true,
    hourlyRate: 3500,
  },
  {
    id: 'worker2',
    name: 'Fatima Abdullahi',
    username: 'fatima_clean',
    role: 'worker',
    bio: 'Professional cleaner, 5 years experience. Deep clean specialist. Trusted by over 20 families in Wukari.',
    skills: ['Cleaning', 'Laundry', 'Cooking'],
    rating: 4.8,
    completedJobs: 62,
    location: 'North Wukari',
    available: true,
    hourlyRate: 2000,
    shopId: 'shop2',
  },
  {
    id: 'worker3',
    name: 'Ibrahim Musa',
    username: 'ibrahim_electric',
    role: 'worker',
    bio: 'Certified electrician. Solar installation, wiring, generator repairs. 10 years in the trade.',
    skills: ['Electrical', 'Generator Repair', 'Solar'],
    rating: 4.7,
    completedJobs: 28,
    location: 'South Wukari',
    available: false,
    hourlyRate: 4000,
  },
  {
    id: 'worker4',
    name: 'Emeka Eze',
    username: 'emeka_carpenter',
    role: 'worker',
    bio: 'Carpenter and furniture maker. Custom builds, repairs, installations. Quality craftsmanship guaranteed.',
    skills: ['Carpentry', 'Furniture', 'Roofing'],
    rating: 4.6,
    completedJobs: 19,
    location: 'Central Wukari',
    available: true,
    hourlyRate: 3000,
  },
  {
    id: 'worker5',
    name: 'Grace Adeyemi',
    username: 'grace_builds',
    role: 'worker',
    bio: 'Construction and renovation specialist. Tiling, plastering, painting. Over 15 years on site.',
    skills: ['Construction', 'Tiling', 'Painting'],
    rating: 4.9,
    completedJobs: 47,
    location: 'North Wukari',
    available: true,
    hourlyRate: 3800,
  },
  {
    id: 'worker6',
    name: 'Yusuf Garba',
    username: 'yusuf_welder',
    role: 'worker',
    bio: 'Welder and fabricator. Gates, grills, structural steel. Mobile workshop, come to you.',
    skills: ['Welding', 'Fabrication', 'Security'],
    rating: 4.5,
    completedJobs: 23,
    location: 'South Wukari',
    available: true,
    hourlyRate: 4500,
  },
  {
    id: 'worker7',
    name: 'Ngozi Obi',
    username: 'ngozi_kitchen',
    role: 'worker',
    bio: 'Cook and caterer. Can prepare for events, daily home cooking, or office catering. Hygiene-certified.',
    skills: ['Cooking', 'Catering', 'Cleaning'],
    rating: 5.0,
    completedJobs: 81,
    location: 'Central Wukari',
    available: false,
    hourlyRate: 2500,
    shopId: 'shop5',
  },
  {
    id: 'worker8',
    name: 'Bello Abubakar',
    username: 'bello_mechanic',
    role: 'worker',
    bio: 'Auto mechanic and generator technician. Diagnose, repair, maintain. 12 years hands-on experience.',
    skills: ['Auto Repair', 'Generator Repair', 'AC Repair'],
    rating: 4.7,
    completedJobs: 55,
    location: 'North Wukari',
    available: true,
    hourlyRate: 3200,
    shopId: 'shop4',
  },
  {
    id: 'worker_hassan',
    name: 'Hassan Abubakar',
    username: 'hassan_cuts',
    role: 'worker',
    bio: 'Premium barber, 7 years. Fades, shaves, full grooming. Walk-ins welcome at Market Road.',
    skills: ['Barbing', 'Grooming'],
    rating: 4.9,
    completedJobs: 200,
    location: 'Central Wukari',
    available: true,
    hourlyRate: 1500,
    shopId: 'shop1',
  },
  {
    id: 'worker_ngozi',
    name: 'Ngozi Eze',
    username: 'ngozi_fashion',
    role: 'worker',
    bio: 'Bespoke tailor specialising in traditional and modern styles. Zaria Street, Central Wukari.',
    skills: ['Tailoring', 'Fashion Design', 'Embroidery'],
    rating: 4.7,
    completedJobs: 34,
    location: 'Central Wukari',
    available: true,
    hourlyRate: 5000,
    shopId: 'shop3',
  },
]